services:
  db:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: fingerprint-db
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Nairobi
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=fpsnsdb
      - MYSQL_USER=fp_user
      - MYSQL_PASSWORD=fp_pass
    volumes:
      - db_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
    ports:
      - "3306:3306"
    networks:
      - app_network
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      interval: 5s
      timeout: 5s
      retries: 10

  web:
    build: .
    container_name: fingerprint-web
    privileged: true
    depends_on:
      db:
        condition: service_healthy
    environment:
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=5000
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=fpsnsdb
      - DB_USER=fp_user
      - DB_PASSWORD=fp_pass
      - SMTP_HOST=smtp.office365.com
      - SMTP_PORT=587
      - SMTP_USERNAME=attendance@stnicholasschools.sc.ke
      - SMTP_PASSWORD=RCT@2025
    ports:
      - "80:5000"
    devices:
      - "/dev/serial0:/dev/serial0"
    networks:
      - app_network

volumes:
  db_data:


networks:
  app_network:
    driver: bridge
